import { Base64 } from "js-base64";

export let wasm: DotNetModule;

export interface DotNetModule extends EmscriptenModule {
    MONO: any,
    BINDING: any,
    ccall(ident: string,
          returnType: Emscripten.JSType | null,
          argTypes: Emscripten.JSType[],
          args: Emscripten.TypeCompatibleWithC[],
          opts?: Emscripten.CCallOpts): any;
}

export function initializeWasm(): Promise<void> {
    return new Promise<void>(resolve => {
        // "Module" global is expected in the emscripten's autogenerated js wrapper.
        global["Module"] = wasm = {
            wasmBinary: loadBinary(),
            onRuntimeInitialized: resolve
        } as any;
        require("../runtime/artifacts/bin/native/net6.0-Browser-Release-wasm/dotnet.js")(wasm);
    });
}

export function destroyWasm(): void {
    // EM.ccall("emscripten_force_exit", null, ["number"], [0]);
    // TODO: Find out how to destroy emscripten module (or if it's necessary).
}

function loadBinary(): Uint8Array {
    const base64Url = require("../runtime/artifacts/bin/native/net6.0-Browser-Release-wasm/dotnet.wasm");
    const base64 = base64Url.split(",")[1];
    return Base64.toUint8Array(base64);
}
