namespace Bootsharp.Publish;

/// <summary>
/// Generates interceptors for <see cref="JSEventAttribute"/> methods
/// in the solution (except methods generated by <see cref="ImportGenerator"/>).
/// </summary>
public class EventGenerator
{

}
