namespace Bootsharp.Publish;

/// <summary>
/// Generates interceptors for <see cref="JSFunctionAttribute"/> methods
/// in the solution (except methods generated by <see cref="ImportGenerator"/>).
/// </summary>
internal sealed class FunctionGenerator
{
    public string Generate (AssemblyInspection inspection) => "";
}
