namespace Bootsharp.Publish;

/// <summary>
/// Generates hints for DotNet to not trim classes with
/// <see cref="JSInvokableAttribute"/> methods (they're used by
/// generated interop bindings, which is not obvious for DotNet), except
/// methods generated by <see cref="ExportGenerator"/>.
/// </summary>
internal sealed class InvokableGenerator
{
    public string Generate (AssemblyInspection inspection) => "";
}
