namespace Bootsharp;

/// <summary>
/// Manages exported (C# -> JavaScript) and imported (JavaScript -> C#) instances.
/// </summary>
/// <remarks>
/// Exported instances originate from C# and are created in the user code;
/// we track them to be able to invoke their members in the static bindings.
/// Imported instances originate from JS and are represented with the C# proxies generated by Bootsharp;
/// we track them to be able to invoke their event raisers in the static bindings.
/// </remarks>
public static class Instances
{
    /// <summary>
    /// Invoked on <see cref="Export"/> when registering an exported instance.
    /// </summary>
    /// <param name="id">The unique identifier of the instance.</param>
    /// <param name="it">The registered instance or the specialized wrapper, when applicable.</param>
    /// <returns>The callback to invoke when disposing the instance.</returns>
    public delegate Action ExportCallback (int id, object it);

    private static readonly Dictionary<int, WeakReference> importedById = [];
    private static readonly Dictionary<Type, Func<int, object>> importers = [];
    private static readonly Dictionary<Type, (Func<object, object>? spec, ExportCallback? cb)> exporters = [];
    private static readonly Dictionary<int, object> exportedById = [];
    private static readonly Dictionary<object, int> idByExported = new(ReferenceEqualityComparer.Instance);
    private static readonly Dictionary<int, Action> onDisposeById = [];
    private static readonly Queue<int> idPool = [];
    private static int nextId = int.MinValue; // C# IDs are negative; JS's — positive; 0 reserved for null.

    /// <summary>
    /// Resolves a registered instance associated with the specified ID, or uses a factory that
    /// was registered with <see cref="RegisterImport"/> to register a new imported instance.
    /// </summary>
    public static T? Resolve<T> (int id)
    {
        if (id == 0) return default;
        if (id < 0) return UnwrapExport(exportedById[id]);
        if (importedById.GetValueOrDefault(id) is { } weak) return UnwrapImport(weak.Target!);
        var it = importers[typeof(T)](id);
        importedById[id] = new(it);
        return UnwrapImport(it);

        static T UnwrapImport (object o) => o is T t ? t : (T)((SpecializedImport)o).Unwrap();
        static T UnwrapExport (object o) => o is T t ? t : (T)((SpecializedExport)o)._it;
    }

    /// <summary>
    /// Registers specified exported (C#) instance and returns the associated unique ID.
    /// Short-circuits already registered exported and imported instances.
    /// Invokes applicable exporters registered with <see cref="RegisterExport"/>.
    /// </summary>
    /// <param name="it">The instance to register.</param>
    /// <returns>Unique ID associated with the registered instance.</returns>
    public static int Export<T> (T? it)
    {
        if (it is null) return 0;
        if (it is JSProxy js) return js._id;
        if (it is Delegate { Target: JSProxy del }) return del._id;
        if (idByExported.TryGetValue(it, out var id)) return id;
        exporters.TryGetValue(typeof(T), out var exporter);
        var stored = exporter.spec is { } specialize ? specialize(it) : it;
        if (stored is SpecializedExport { _it: JSProxy ejs }) return ejs._id;
        id = idPool.Count > 0 ? idPool.Dequeue() : nextId++;
        exportedById[idByExported[Key(stored)] = id] = stored;
        if (exporter.cb is { } cb) onDisposeById[id] = cb(id, stored);
        return id;
    }

    /// <summary>
    /// Returns a registered exported instance associated with the specified ID.
    /// </summary>
    public static T Exported<T> (int id) where T : class
    {
        return (T)exportedById[id];
    }

    /// <summary>
    /// Notifies that an exported instance with the specified ID is no longer used on the JavaScript side
    /// (eg, was garbage collected) and can be released on the C# side as well.
    /// </summary>
    public static void DisposeExported (int id)
    {
        if (exportedById.Remove(id, out var it)) idByExported.Remove(Key(it));
        if (onDisposeById.Remove(id, out var onDispose)) onDispose();
        idPool.Enqueue(id);
    }

    /// <summary>
    /// Registers a factory for creating binding proxy of a JS-originated instance of the specified type.
    /// </summary>
    public static void RegisterImport (Type type, Func<int, object> factory)
    {
        importers[type] = factory;
    }

    /// <summary>
    /// Registers special handling for exported (C#) instances of the specified type.
    /// Specialized exports register their wrapper factory with the <paramref name="spec"/> function.
    /// Instances requiring custom callbacks on construction and disposal use <paramref name="cb"/> delegate.
    /// </summary>
    public static void RegisterExport (Type type, Func<object, object>? spec, ExportCallback? cb = null)
    {
        exporters[type] = (spec, cb);
    }

    /// <summary>
    /// Notifies that an imported interop instance with the specified ID is no longer used
    /// on the C# side and can be untracked.
    /// </summary>
    public static void DisposeImported (int id)
    {
        importedById.Remove(id);
    }

    private static object Key (object it)
    {
        // preserves specialized export instance identity
        return it is SpecializedExport sp ? sp._it : it;
    }
}
