name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: cover
        run: |
          cd src/js
          npm install
          npm run build
          cd ../cs
          bash ./.scripts/llvm.sh
          bash ./.scripts/pack.sh
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute
          cd ../js
          dotnet workload restore
          npm run compile-test
          npm run cover
      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
